/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ServerStarter */

#ifndef _Included_ServerStarter
#define _Included_ServerStarter
#ifdef __cplusplus
extern "C" {
#endif
#undef ServerStarter_FOCUS_TRAVERSABLE_UNKNOWN
#define ServerStarter_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef ServerStarter_FOCUS_TRAVERSABLE_DEFAULT
#define ServerStarter_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef ServerStarter_FOCUS_TRAVERSABLE_SET
#define ServerStarter_FOCUS_TRAVERSABLE_SET 2L
#undef ServerStarter_TOP_ALIGNMENT
#define ServerStarter_TOP_ALIGNMENT 0.0f
#undef ServerStarter_CENTER_ALIGNMENT
#define ServerStarter_CENTER_ALIGNMENT 0.5f
#undef ServerStarter_BOTTOM_ALIGNMENT
#define ServerStarter_BOTTOM_ALIGNMENT 1.0f
#undef ServerStarter_LEFT_ALIGNMENT
#define ServerStarter_LEFT_ALIGNMENT 0.0f
#undef ServerStarter_RIGHT_ALIGNMENT
#define ServerStarter_RIGHT_ALIGNMENT 1.0f
#undef ServerStarter_serialVersionUID
#define ServerStarter_serialVersionUID -7644114512714619750LL
#undef ServerStarter_serialVersionUID
#define ServerStarter_serialVersionUID 4613797578919906343LL
#undef ServerStarter_INCLUDE_SELF
#define ServerStarter_INCLUDE_SELF 1L
#undef ServerStarter_SEARCH_HEAVYWEIGHTS
#define ServerStarter_SEARCH_HEAVYWEIGHTS 1L
#undef ServerStarter_OPENED
#define ServerStarter_OPENED 1L
#undef ServerStarter_serialVersionUID
#define ServerStarter_serialVersionUID 4497834738069338734LL
#undef ServerStarter_DEFAULT_CURSOR
#define ServerStarter_DEFAULT_CURSOR 0L
#undef ServerStarter_CROSSHAIR_CURSOR
#define ServerStarter_CROSSHAIR_CURSOR 1L
#undef ServerStarter_TEXT_CURSOR
#define ServerStarter_TEXT_CURSOR 2L
#undef ServerStarter_WAIT_CURSOR
#define ServerStarter_WAIT_CURSOR 3L
#undef ServerStarter_SW_RESIZE_CURSOR
#define ServerStarter_SW_RESIZE_CURSOR 4L
#undef ServerStarter_SE_RESIZE_CURSOR
#define ServerStarter_SE_RESIZE_CURSOR 5L
#undef ServerStarter_NW_RESIZE_CURSOR
#define ServerStarter_NW_RESIZE_CURSOR 6L
#undef ServerStarter_NE_RESIZE_CURSOR
#define ServerStarter_NE_RESIZE_CURSOR 7L
#undef ServerStarter_N_RESIZE_CURSOR
#define ServerStarter_N_RESIZE_CURSOR 8L
#undef ServerStarter_S_RESIZE_CURSOR
#define ServerStarter_S_RESIZE_CURSOR 9L
#undef ServerStarter_W_RESIZE_CURSOR
#define ServerStarter_W_RESIZE_CURSOR 10L
#undef ServerStarter_E_RESIZE_CURSOR
#define ServerStarter_E_RESIZE_CURSOR 11L
#undef ServerStarter_HAND_CURSOR
#define ServerStarter_HAND_CURSOR 12L
#undef ServerStarter_MOVE_CURSOR
#define ServerStarter_MOVE_CURSOR 13L
#undef ServerStarter_NORMAL
#define ServerStarter_NORMAL 0L
#undef ServerStarter_ICONIFIED
#define ServerStarter_ICONIFIED 1L
#undef ServerStarter_MAXIMIZED_HORIZ
#define ServerStarter_MAXIMIZED_HORIZ 2L
#undef ServerStarter_MAXIMIZED_VERT
#define ServerStarter_MAXIMIZED_VERT 4L
#undef ServerStarter_MAXIMIZED_BOTH
#define ServerStarter_MAXIMIZED_BOTH 6L
#undef ServerStarter_serialVersionUID
#define ServerStarter_serialVersionUID 2673458971256075116LL
#undef ServerStarter_EXIT_ON_CLOSE
#define ServerStarter_EXIT_ON_CLOSE 3L
#ifdef __cplusplus
}
#endif
#endif
